spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: "jdbc:mysql://localhost:3306/anony"
    username: "sputnik"
    password: "112358"

server:
  port: 3001
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

anony:
  jwt:
    secret: c5d01695-d05f-521b-89db-70bb498b79b1
    expiration: 300000