spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "create-drop"
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: "jdbc:h2:mem:dev"

server:
  port: 3001
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false

anony:
  jwt:
    secret: c5d01695-d05f-521b-89db-70bb498b79b1
    expiration: 300000